import { Module } from '../../core/interfaces/module.js';

function call(target, names, ...args) { for (const name of names) { try { if (typeof target?.[name] === 'function') { const value = target[name](...args); if (value != null) return value; } } catch {} } return null; }
function values(collection) { const source = collection?.d ?? collection?.l ?? collection ?? []; return Array.isArray(source) ? source.filter(Boolean) : Object.values(source).filter(Boolean); }

export class SupportManagerModule extends Module {
  constructor() { super({ id: 'support-manager', name: 'Support Manager', version: '0.1.0', apiVersion: '1.0.0', author: 'ProfessorSr', description: 'Inspect, manually recall, and manually calibrate support weapons.', permissions: ['game', 'notifications', 'windows'], settings: {} }); }
  async enable(context) { this.context = context; }
  root() { return this.context?.hub?.game?.services?.tryGet?.('clientLib')?.root ?? globalThis.ClientLib; }
  citiesObject() { return call(this.root()?.Data?.MainData?.GetInstance?.(), ['get_Cities']); }
  cities() { return values(call(this.citiesObject(), ['get_AllCities'])); }
  rows() { return this.cities().map((city) => { const weapon = call(city, ['get_SupportWeapon']), status = call(city, ['get_SupportWeaponStatus']); return { raw: city, id: call(city, ['get_Id']), name: String(call(city, ['get_Name']) ?? 'Base'), weapon: String(call(weapon, ['get_Name', 'get_DisplayName']) ?? weapon?.dn ?? 'None'), level: Number(call(city, ['get_SupportLevel']) ?? call(weapon, ['get_Level']) ?? 0), targetId: call(city, ['get_DedicatedSupportId', 'get_SupportTargetId']) ?? status?.TargetId ?? 0, state: String(status?.Status ?? call(city, ['get_SupportWeaponState']) ?? 'Ready') }; }); }
  selectedTarget() { const cities = this.citiesObject(), target = call(cities, ['get_CurrentCity']); return { id: call(target, ['get_Id']), name: String(call(target, ['get_Name']) ?? 'selected base'), x: Number(call(target, ['get_PosX']) ?? 0), y: Number(call(target, ['get_PosY']) ?? 0) }; }
  confirm(message) { return globalThis.confirm?.(message) ?? false; }
  recall(city) { if (!city || !this.confirm(`Recall the support weapon assigned by ${call(city, ['get_Name'])}?`)) return false; if (typeof city.RecallDedicatedSupport !== 'function') throw new Error('Support recall is unavailable in this game build.'); city.RecallDedicatedSupport(); return true; }
  calibrate(city, target = this.selectedTarget(), confirmed = false) { if (!city || !target.id) throw new Error('Select a valid target base on the world map first.'); const weapon = call(city, ['get_SupportWeapon']); if (!weapon) throw new Error('This base has no support weapon.'); const range = Number(call(weapon, ['get_Range', 'get_SupportRange']) ?? weapon?.r ?? Infinity); const distance = Math.hypot(Number(call(city, ['get_PosX', 'get_X']) ?? 0) - target.x, Number(call(city, ['get_PosY', 'get_Y']) ?? 0) - target.y); if (distance > range) throw new Error(`${target.name} is outside this support weapon's range.`); if (!confirmed && !this.confirm(`Calibrate support from ${call(city, ['get_Name'])} on ${target.name}?`)) return false; if (typeof city.SetDedicatedSupport !== 'function') throw new Error('Support calibration is unavailable in this game build.'); city.SetDedicatedSupport(target.id); return true; }
  selectedRow() { const index = this.table.getSelectionModel?.().getLeadSelectionIndex?.() ?? -1; return this.currentRows[index] ?? null; }
  render() { this.currentRows = this.rows(); this.model.setData(this.currentRows.map((row) => [row.name, row.weapon, row.level, row.targetId || 'None', row.state])); this.target.setValue(`Calibration target: ${this.selectedTarget().name}`); }
  build() { const qx = globalThis.qx, root = new qx.ui.container.Composite(new qx.ui.layout.VBox(7)).set({ padding: 9 }); this.target = new qx.ui.basic.Label('').set({ textColor: '#fff' }); root.add(this.target); this.model = new qx.ui.table.model.Simple(); this.model.setColumns(['Base', 'Support', 'Level', 'Assigned target', 'State']); this.table = new qx.ui.table.Table(this.model); root.add(this.table, { flex: 1 }); const actions = new qx.ui.container.Composite(new qx.ui.layout.HBox(6)); const recall = new qx.ui.form.Button('Recall Selected'), recallAll = new qx.ui.form.Button('Recall All'), calibrate = new qx.ui.form.Button('Calibrate Selected'), calibrateAll = new qx.ui.form.Button('Calibrate All in Range'), refresh = new qx.ui.form.Button('Refresh'); for (const button of [recall, recallAll, calibrate, calibrateAll, refresh]) actions.add(button); root.add(actions); recall.addListener('execute', () => { const row = this.selectedRow(); if (row && this.recall(row.raw)) this.render(); }); recallAll.addListener('execute', () => { if (!this.confirm('Recall every currently assigned support weapon?')) return; for (const row of this.currentRows.filter((item) => item.targetId)) row.raw.RecallDedicatedSupport?.(); this.render(); }); calibrate.addListener('execute', () => { const row = this.selectedRow(); if (row && this.calibrate(row.raw)) this.render(); }); calibrateAll.addListener('execute', () => { const target = this.selectedTarget(); if (!this.confirm(`Calibrate every support weapon in range on ${target.name}?`)) return; for (const row of this.currentRows) { try { this.calibrate(row.raw, target, true); } catch {} } this.render(); }); refresh.addListener('execute', () => this.render()); this.render(); return root; }
  async open(context = this.context) { if (!this.context) await this.enable(context); if (this.record?.window && !this.record.window.isDisposed?.()) { this.render(); this.record.window.open(); return this.record; } this.record = await this.context.windows.open({ id: 'support-manager', title: 'Support Manager', content: this.build(), x: 130, y: 80, width: 820, height: 520, resizable: true, singleton: true }); return this.record; }
  async disable(context = this.context) { context?.windows?.close?.('support-manager'); this.record = null; this.context = null; }
}
export default SupportManagerModule;
