import { Module } from '../../core/interfaces/module.js';

function call(target, names, ...args) { for (const name of names) { try { if (typeof target?.[name] === 'function') { const value = target[name](...args); if (value != null) return value; } } catch {} } return null; }
const COLORS = Object.freeze({ own: '#30b9ff', alliance: '#39d353', enemy: '#ff4d4d', neutral: '#d8c36a', forgotten: '#f1c232', poi: '#c084fc' });
function escape(value) { return String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;'); }

export class TacticalMapModule extends Module {
  constructor() { super({ id: 'tactical-map', name: 'Tactical Map', version: '1.0.0', apiVersion: '1.0.0', author: 'ProfessorSr', description: 'Regional map, relationship colors, POI filters, target lines, and PvP quick-map mode.', permissions: ['game', 'storage', 'settings', 'windows'], settings: { radius: { type: 'number', default: 25, min: 5, max: 75 }, zoom: { type: 'number', default: 10, min: 4, max: 24 }, minLevel: { type: 'number', default: 1, min: 1, max: 100 }, showForgotten: { type: 'boolean', default: true }, showPlayers: { type: 'boolean', default: true }, showPois: { type: 'boolean', default: true }, showLines: { type: 'boolean', default: true }, pvpOnly: { type: 'boolean', default: false } } }); }
  async enable(context) { this.context = context; this.savedTargets = new Set((await context.storage.get('module:war-room:formation-presets:v1', [])).map((preset) => `${preset.target?.x}:${preset.target?.y}`)); }
  root() { return this.context?.hub?.game?.services?.tryGet?.('clientLib')?.root ?? globalThis.ClientLib; }
  state() { const root = this.root(), main = root?.Data?.MainData?.GetInstance?.(), cities = call(main, ['get_Cities']), current = call(cities, ['get_CurrentCity', 'get_CurrentOwnCity']), own = call(cities, ['get_CurrentOwnCity']), alliance = call(main, ['get_Alliance']); return { root, main, world: call(main, ['get_World']), center: { x: Number(call(current, ['get_PosX']) ?? call(own, ['get_PosX']) ?? 0), y: Number(call(current, ['get_PosY']) ?? call(own, ['get_PosY']) ?? 0) }, ownIds: new Set(Object.values(call(cities, ['get_AllCities'])?.d ?? {}).map((city) => String(call(city, ['get_Id'])))), allianceId: call(alliance, ['get_Id']) }; }
  classify(object, state) { const name = String(object?.constructor?.name ?? '').toLowerCase(), id = call(object, ['getID', 'get_Id', 'get_BaseId']), allianceId = call(object, ['get_AllianceId', 'get_OwnerAllianceId']), type = Number(call(object, ['get_Type', 'get_ObjectType']) ?? object?.Type ?? 0); let category = 'neutral'; if (state.ownIds.has(String(id))) category = 'own'; else if (/npcbase|npccamp|forgotten/.test(name) || type === 2 || type === 3) category = 'forgotten'; else if (/poi|pointofinterest/.test(name) || type >= 4) category = 'poi'; else if (allianceId && String(allianceId) === String(state.allianceId)) category = 'alliance'; else if (allianceId) category = 'enemy'; return { id, category, type, level: Number(call(object, ['get_BaseLevel', 'get_Level']) ?? 0), allianceId, name: String(call(object, ['get_Name', 'get_AllianceName']) ?? category) }; }
  objects() { const state = this.state(), radius = this.radius?.getValue?.() ?? this.context.moduleSettings.get('radius', 25), minLevel = this.minLevel?.getValue?.() ?? this.context.moduleSettings.get('minLevel', 1), result = []; for (let y = state.center.y - radius; y <= state.center.y + radius; y += 1) for (let x = state.center.x - radius; x <= state.center.x + radius; x += 1) { const object = state.world?.GetObjectFromPosition?.(x, y); if (!object) continue; const item = { ...this.classify(object, state), x, y }; if (item.level < minLevel) continue; if (this.pvpOnly?.getValue?.() && !['own', 'alliance', 'enemy', 'neutral'].includes(item.category)) continue; if (item.category === 'forgotten' && !this.showForgotten?.getValue?.()) continue; if (item.category === 'poi' && !this.showPois?.getValue?.()) continue; if (!['forgotten', 'poi'].includes(item.category) && !this.showPlayers?.getValue?.()) continue; result.push(item); } return { ...state, radius, result }; }
  svg() { const state = this.objects(), scale = this.zoom?.getValue?.() ?? 10, size = state.radius * 2 * scale + 30, point = (value, origin) => 15 + (value - origin + state.radius) * scale; const lines = this.showLines?.getValue?.() ? state.result.filter((item) => item.category === 'enemy').map((item) => `<line x1="${size / 2}" y1="${size / 2}" x2="${point(item.x, state.center.x)}" y2="${point(item.y, state.center.y)}" stroke="${COLORS.enemy}" stroke-opacity=".22"/>`).join('') : ''; const objects = state.result.map((item) => `<g>${this.savedTargets?.has(`${item.x}:${item.y}`) ? `<circle cx="${point(item.x, state.center.x)}" cy="${point(item.y, state.center.y)}" r="9" fill="none" stroke="#fff" stroke-width="2"/>` : ''}<circle cx="${point(item.x, state.center.x)}" cy="${point(item.y, state.center.y)}" r="${item.category === 'poi' ? 4 : 5}" fill="${COLORS[item.category]}" stroke="#111"><title>${escape(item.name)} L${item.level} ${item.x}:${item.y}</title></circle></g>`).join(''); return `<div style="background:#161b22;overflow:auto;width:100%;height:100%;color:white"><svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" style="background:#202830">${lines}<path d="M ${size / 2 - 7} ${size / 2} h14 M ${size / 2} ${size / 2 - 7} v14" stroke="white"/>${objects}</svg></div>`; }
  render() { this.map.setValue(this.svg()); const count = this.objects().result.length; this.status.setValue(`${count} objects around ${this.state().center.x}:${this.state().center.y}. Colors: own blue, alliance green, enemy red, neutral tan, Forgotten gold, POI purple.`); }
  control(label, widget, root) { root.add(new globalThis.qx.ui.basic.Label(label).set({ textColor: '#fff', alignY: 'middle' })); root.add(widget); }
  build() { const qx = globalThis.qx, root = new qx.ui.container.Composite(new qx.ui.layout.VBox(6)).set({ padding: 7 }), controls = new qx.ui.container.Composite(new qx.ui.layout.Flow(6, 4)); this.radius = new qx.ui.form.Spinner(5, this.context.moduleSettings.get('radius', 25), 75); this.zoom = new qx.ui.form.Spinner(4, this.context.moduleSettings.get('zoom', 10), 24); this.minLevel = new qx.ui.form.Spinner(1, this.context.moduleSettings.get('minLevel', 1), 100); this.control('Radius', this.radius, controls); this.control('Scale', this.zoom, controls); this.control('Min level', this.minLevel, controls); for (const [property, label, setting] of [['showPlayers', 'Players', 'showPlayers'], ['showForgotten', 'Forgotten', 'showForgotten'], ['showPois', 'POIs', 'showPois'], ['showLines', 'Target lines', 'showLines'], ['pvpOnly', 'PvP quick map', 'pvpOnly']]) { this[property] = new qx.ui.form.CheckBox(label).set({ value: this.context.moduleSettings.get(setting, setting !== 'pvpOnly'), textColor: '#fff' }); controls.add(this[property]); this[property].addListener('changeValue', (event) => { void this.context.moduleSettings.set(setting, event.getData()); this.render(); }); } const refresh = new qx.ui.form.Button('Use Current Selection'); controls.add(refresh); root.add(controls); for (const [widget, setting] of [[this.radius, 'radius'], [this.zoom, 'zoom'], [this.minLevel, 'minLevel']]) widget.addListener('changeValue', (event) => { void this.context.moduleSettings.set(setting, event.getData()); this.render(); }); refresh.addListener('execute', () => this.render()); this.status = new qx.ui.basic.Label('').set({ textColor: '#fff', wrap: true }); root.add(this.status); this.map = new qx.ui.basic.Label('').set({ rich: true, selectable: false }); const mapScroll = new qx.ui.container.Scroll(); mapScroll.add(this.map); root.add(mapScroll, { flex: 1 }); this.render(); return root; }
  async open(context = this.context) { if (!this.context) await this.enable(context); if (this.record?.window && !this.record.window.isDisposed?.()) { this.render(); this.record.window.open(); return this.record; } this.record = await this.context.windows.open({ id: 'tactical-map', title: 'Tactical Map', content: this.build(), x: 80, y: 60, width: 900, height: 700, resizable: true, singleton: true }); return this.record; }
  async disable(context = this.context) { context?.windows?.close?.('tactical-map'); this.record = null; this.context = null; }
}
export default TacticalMapModule;
