import { Module } from '../../core/interfaces/module.js';

export class UiToolsModule extends Module {
  constructor() { super({ id: 'ui-tools', name: 'UI Tools', version: '0.3.0', apiVersion: '1.0.0', author: 'ProfessorSr', description: 'Make compatible native overlays movable and manage Suite window modes.', permissions: ['events', 'windows'], settings: {} }); this.adjusted = new Set(); this.lastRegistryScanAt = 0; }
  async enable(context) { this.context = context; const apply = () => { const now = Date.now(); if (now - this.lastRegistryScanAt < 10000) return; this.lastRegistryScanAt = now; this.apply(); }; context.events.on('game:tick', apply); this.lastRegistryScanAt = Date.now(); this.apply(); }
  apply() { const registry = globalThis.qx?.core?.ObjectRegistry?.getRegistry?.() ?? {}; for (const widget of Object.values(registry)) { const name = String(widget?.classname ?? widget?.constructor?.classname ?? ''); if (!/(Mail|Forum|Message).*Overlay|Overlay.*(Mail|Forum|Message)/i.test(name)) continue; try { widget.setMovable?.(true); widget.setUseMoveFrame?.(true); this.adjusted.add(widget); } catch {} } }
  records() { return [...(this.context?.windows?.windows?.values?.() ?? [])].filter((record) => record.id !== 'ui-tools' && !record.window?.isDisposed?.()); }
  selected() { const id = this.list?.getSelection?.()?.[0]?.getModel?.(); return this.context?.windows?.windows?.get?.(id) ?? null; }
  render() { if (!this.status) return; this.status.setValue(`${[...this.adjusted].filter((widget) => !widget.isDisposed?.()).length} compatible native overlays made movable. Window position, size, pin, lock, compact, auto-hide, and visibility state are persisted.`); const selected = this.selected()?.id; this.list.removeAll(); for (const record of this.records()) { const item = new globalThis.qx.ui.form.ListItem(`${record.id}${record.state.pinned ? ' · pinned' : ''}${record.state.locked ? ' · locked' : ''}${record.state.compact ? ' · compact' : ''}${record.state.autoHide ? ' · auto-hide' : ''}`, null, record.id); this.list.add(item); if (record.id === selected) this.list.setSelection([item]); } }
  toggle(method, key) { const record = this.selected(); if (!record) return; record[method]?.(!record.state[key]); this.render(); }
  build() { const qx = globalThis.qx, root = new qx.ui.container.Composite(new qx.ui.layout.VBox(8)).set({ padding: 12, textColor: '#fff' }); this.status = new qx.ui.basic.Label('').set({ textColor: '#fff', wrap: true }); root.add(this.status); this.list = new qx.ui.form.List().set({ height: 180 }); root.add(this.list, { flex: 1 }); const actions = new qx.ui.container.Composite(new qx.ui.layout.Flow(6, 5)); for (const [label, method, key] of [['Pin / Unpin', 'setPinned', 'pinned'], ['Lock / Unlock', 'setLocked', 'locked'], ['Compact / Expand', 'setCompact', 'compact'], ['Auto-hide On / Off', 'setAutoHide', 'autoHide']]) { const button = new qx.ui.form.Button(label); button.addListener('execute', () => this.toggle(method, key)); actions.add(button); } const show = new qx.ui.form.Button('Show Window'); show.addListener('execute', () => { const record = this.selected(); record?.window?.show?.(); record?.window?.setActive?.(true); }); actions.add(show); const refresh = new qx.ui.form.Button('Re-scan UI'); refresh.addListener('execute', () => { this.apply(); this.render(); }); actions.add(refresh); root.add(actions); this.render(); return root; }
  async open(context = this.context) { if (this.record?.window && !this.record.window.isDisposed?.()) { this.render(); this.record.window.open(); return this.record; } this.record = await this.context.windows.open({ id: 'ui-tools', title: 'UI Tools', content: this.build(), x: 240, y: 120, width: 650, height: 440, resizable: true, singleton: true }); return this.record; }
  async disable(context = this.context) { context?.windows?.close?.('ui-tools'); this.adjusted.clear(); this.record = null; this.context = null; }
}
export default UiToolsModule;
